import { useEffect, useMemo, useRef, useState, type ReactNode } from 'react';
import { Bot, CheckCircle2, KeyRound, Mic, RefreshCw, Send, Settings2, Sparkles, Square, Trash2, Volume2 } from 'lucide-react';
import type { AiChatMessage, AiModelOption, AiSettingsView } from '@aviator/shared';
import { Badge, Button, Card } from '@/components/ui';
import { useAppStore } from '@/store/app-store';

const suggestions = ['Resuma os padrões e anomalias desta amostra.', 'Compare a taxa de WIN com o risco e o resultado financeiro.', 'Proponha uma hipótese de estratégia para validar em backtest.', 'Quais dados ainda faltam para uma conclusão confiável?'];
type HistoryLimit = 50 | 100 | 250 | 500 | 1_000 | 2_500 | 5_000 | 10_000;

export function AiAnalystPage() {
  const { platforms, terminals } = useAppStore();
  const [scope,setScope]=useState<'TERMINAL'|'PLATFORM'>(terminals.length?'TERMINAL':'PLATFORM');
  const [terminalId,setTerminalId]=useState(terminals[0]?.id??'');const[platformId,setPlatformId]=useState(platforms[0]?.id??'');
  const [historyLimit,setHistoryLimit]=useState<HistoryLimit>(100);
  const [settings,setSettings]=useState<AiSettingsView|null>(null);const[apiKey,setApiKey]=useState('');const[model,setModel]=useState('openrouter/auto');const[transcriptionModel,setTranscriptionModel]=useState('openai/whisper-1');
  const [models,setModels]=useState<AiModelOption[]>([]);const[settingsOpen,setSettingsOpen]=useState(false);const[message,setMessage]=useState<string|null>(null);
  const [messages,setMessages]=useState<AiChatMessage[]>([]);const[prompt,setPrompt]=useState('');const[sending,setSending]=useState(false);const[lastMeta,setLastMeta]=useState<string|null>(null);
  const [recording,setRecording]=useState(false);const[audioBlob,setAudioBlob]=useState<Blob|null>(null);const[audioUrl,setAudioUrl]=useState<string|null>(null);const[recordingSeconds,setRecordingSeconds]=useState(0);
  const recorderRef=useRef<MediaRecorder|null>(null);const chunksRef=useRef<Blob[]>([]);const timerRef=useRef<number|null>(null);const chatEndRef=useRef<HTMLDivElement|null>(null);
  const selectedName=useMemo(()=>scope==='TERMINAL'?terminals.find(item=>item.id===terminalId)?.name:platforms.find(item=>item.id===platformId)?.name,[scope,terminalId,platformId,terminals,platforms]);

  useEffect(()=>{void loadSettings()},[]);
  useEffect(()=>{chatEndRef.current?.scrollIntoView({behavior:'smooth'})},[messages,sending]);
  useEffect(()=>()=>{if(audioUrl)URL.revokeObjectURL(audioUrl);if(timerRef.current)window.clearInterval(timerRef.current);recorderRef.current?.stream.getTracks().forEach(track=>track.stop())},[audioUrl]);

  async function loadSettings(){const result=await window.aviator.getAiSettings();if(result.ok&&result.data){setSettings(result.data);setModel(result.data.model);setTranscriptionModel(result.data.transcriptionModel);setSettingsOpen(!result.data.hasApiKey)}else setMessage(result.error??'Não foi possível carregar a configuração da IA.');}
  async function saveSettings(clearApiKey=false){setMessage(null);const result=await window.aviator.saveAiSettings({apiKey:apiKey.trim()||null,model,transcriptionModel,clearApiKey});if(result.ok&&result.data){setSettings(result.data);setApiKey('');setMessage(clearApiKey?'Chave removida.':'Configuração protegida e salva.');if(!clearApiKey)setSettingsOpen(false)}else setMessage(result.error??'Não foi possível salvar.');}
  async function testConnection(){setMessage('Testando conexão...');const result=await window.aviator.testAiConnection();setMessage(result.ok&&result.data?`Conexão válida: ${result.data.label}${result.data.limitRemaining==null?'':` • saldo do limite US$ ${result.data.limitRemaining.toFixed(2)}`}`:result.error??'Falha na conexão.');}
  async function loadModels(){setMessage('Carregando modelos disponíveis...');const result=await window.aviator.listAiModels();if(result.ok&&result.data){setModels(result.data);setMessage(`${result.data.length} modelos disponíveis na sua conta.`)}else setMessage(result.error??'Não foi possível carregar os modelos.');}

  async function startRecording(){
    try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});const mimeType=MediaRecorder.isTypeSupported('audio/webm;codecs=opus')?'audio/webm;codecs=opus':'audio/webm';const recorder=new MediaRecorder(stream,{mimeType});chunksRef.current=[];recorder.ondataavailable=event=>{if(event.data.size)chunksRef.current.push(event.data)};recorder.onstop=()=>{const blob=new Blob(chunksRef.current,{type:recorder.mimeType});setAudioBlob(blob);setAudioUrl(previous=>{if(previous)URL.revokeObjectURL(previous);return URL.createObjectURL(blob)});stream.getTracks().forEach(track=>track.stop())};recorder.start();recorderRef.current=recorder;setRecording(true);setRecordingSeconds(0);timerRef.current=window.setInterval(()=>setRecordingSeconds(value=>{if(value>=119){stopRecording();return value}return value+1}),1000)}catch(error){setMessage(error instanceof Error?`Microfone indisponível: ${error.message}`:'Não foi possível acessar o microfone.')}
  }
  function stopRecording(){const recorder=recorderRef.current;if(recorder?.state==='recording')recorder.stop();setRecording(false);if(timerRef.current){window.clearInterval(timerRef.current);timerRef.current=null}}
  function clearAudio(){if(audioUrl)URL.revokeObjectURL(audioUrl);setAudioBlob(null);setAudioUrl(null);setRecordingSeconds(0)}

  async function send(){
    const text=prompt.trim();if(!text&&!audioBlob)return;if(!settings?.hasApiKey){setSettingsOpen(true);setMessage('Cadastre a chave do OpenRouter para iniciar a conversa.');return}
    setSending(true);setMessage(null);const placeholder=text||'🎤 Mensagem de áudio';const previous=[...messages];setMessages([...previous,{role:'user',content:placeholder}]);setPrompt('');
    let audio:null|{data:string;format:'webm'}=null;if(audioBlob)audio={data:await blobToBase64(audioBlob),format:'webm'};
    const result=await window.aviator.sendAiChat({platformId:scope==='PLATFORM'?platformId:null,terminalId:scope==='TERMINAL'?terminalId:null,historyLimit,messages:previous,prompt:text||null,audio});
    if(result.ok&&result.data){const userContent=result.data.transcript?`🎤 ${result.data.transcript}`:placeholder;setMessages([...previous,{role:'user',content:userContent},{role:'assistant',content:result.data.content}]);setLastMeta(`${result.data.analyzedRecords} registros • ${result.data.model}${result.data.usage?` • ${result.data.usage.totalTokens} tokens`:''}`);clearAudio()}else{setMessages(previous);setPrompt(text);setMessage(result.error??'Não foi possível concluir a análise.')}setSending(false);
  }

  return <div className="p-5"><div className="mb-4 flex items-end justify-between"><div><div className="flex items-center gap-2"><h2 className="text-xl font-bold">Analista IA</h2><Badge tone={settings?.hasApiKey?'success':'warning'}>{settings?.hasApiKey?'OpenRouter conectado':'Configuração necessária'}</Badge></div><p className="mt-1 text-xs text-muted">Converse por texto ou áudio sobre históricos, resultados e hipóteses para backtest.</p></div><Button onClick={()=>setSettingsOpen(value=>!value)} className="border-line bg-panel text-muted"><Settings2 size={14}/>OpenRouter</Button></div>
    {message&&<div className="mb-3 rounded-md border border-brand/25 bg-brand/10 p-3 text-xs text-blue-100">{message}</div>}
    {settingsOpen&&<Card className="mb-3 p-4"><div className="grid gap-3 xl:grid-cols-[1fr_1fr_1fr_auto]"><Field label="Chave da API"><div className="input-wrap"><KeyRound size={14}/><input type="password" value={apiKey} onChange={e=>setApiKey(e.target.value)} placeholder={settings?.maskedApiKey??'sk-or-v1-...'}/></div></Field><Field label="Modelo de análise"><input list="ai-models" className="mt-1.5 h-10 w-full px-3 text-xs" value={model} onChange={e=>setModel(e.target.value)}/></Field><Field label="Modelo de transcrição"><input className="mt-1.5 h-10 w-full px-3 text-xs" value={transcriptionModel} onChange={e=>setTranscriptionModel(e.target.value)}/></Field><div className="flex items-end gap-2"><Button onClick={()=>void saveSettings()} className="bg-brand text-white">Salvar</Button><Button onClick={()=>void testConnection()} disabled={!settings?.hasApiKey} title="Testar conexão" className="border-line bg-elevated text-muted"><CheckCircle2 size={14}/></Button><Button onClick={()=>void loadModels()} disabled={!settings?.hasApiKey} title="Atualizar modelos" className="border-line bg-elevated text-muted"><RefreshCw size={14}/></Button></div></div><datalist id="ai-models">{models.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</datalist><div className="mt-3 flex items-center text-[10px] text-muted"><KeyRound size={12} className="mr-2 text-success"/>A chave é criptografada pelo sistema operacional e nunca retorna para a interface.{settings?.hasApiKey&&<button onClick={()=>void saveSettings(true)} className="ml-auto text-danger hover:underline">Remover chave</button>}</div></Card>}
    <div className="grid min-h-[calc(100vh-190px)] gap-3 xl:grid-cols-[290px_minmax(0,1fr)]"><Card className="self-start p-4"><div className="label mb-3">Contexto da análise</div><div className="grid grid-cols-2 gap-2"><ScopeButton active={scope==='TERMINAL'} onClick={()=>setScope('TERMINAL')}>Terminal</ScopeButton><ScopeButton active={scope==='PLATFORM'} onClick={()=>setScope('PLATFORM')}>Plataforma</ScopeButton></div><Field label={scope==='TERMINAL'?'Terminal':'Plataforma'}><select className="mt-1.5 h-10 w-full px-3 text-xs" value={scope==='TERMINAL'?terminalId:platformId} onChange={e=>scope==='TERMINAL'?setTerminalId(e.target.value):setPlatformId(e.target.value)}>{(scope==='TERMINAL'?terminals:platforms).map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Amostra histórica"><select className="mt-1.5 h-10 w-full px-3 text-xs" value={historyLimit} onChange={e=>setHistoryLimit(Number(e.target.value) as HistoryLimit)}>{[50,100,250,500,1_000,2_500,5_000,10_000].map(value=><option key={value} value={value}>{value.toLocaleString('pt-BR')} registros</option>)}</select></Field><div className="mt-2 text-[9px] leading-4 text-muted">Até 10.000 registros entram nos cálculos estatísticos; os mais recentes seguem detalhados para preservar o contexto da conversa.</div><div className="mt-4 rounded-md border border-warning/25 bg-warning/5 p-3 text-[10px] leading-4 text-muted">A IA identifica padrões e propõe testes, mas não prevê rodadas nem garante lucro. Valide sugestões no backtest antes de qualquer decisão.</div><Button onClick={()=>{setMessages([]);setLastMeta(null)}} disabled={!messages.length} className="mt-3 w-full border-line bg-elevated text-muted"><Trash2 size={13}/>Limpar conversa</Button></Card>
      <Card className="flex min-h-[620px] min-w-0 flex-col overflow-hidden"><div className="flex items-center border-b border-line px-4 py-3"><div className="grid h-8 w-8 place-items-center rounded-md bg-brand/10 text-blue-300"><Sparkles size={16}/></div><div className="ml-3"><div className="text-xs font-semibold">Análise de {selectedName??'histórico'}</div><div className="mt-0.5 text-[9px] text-muted">Modelo: {settings?.model??model} • contexto atualizado a cada pergunta</div></div>{lastMeta&&<div className="ml-auto font-mono text-[9px] text-muted">{lastMeta}</div>}</div><div className="scrollbar flex-1 space-y-4 overflow-y-auto p-5">{messages.length===0&&<div className="grid h-full min-h-[330px] place-items-center text-center"><div><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-brand/10 text-blue-300"><Bot size={28}/></div><h3 className="mt-4 text-sm font-semibold">O que deseja investigar?</h3><p className="mx-auto mt-1 max-w-md text-xs leading-5 text-muted">Selecione o contexto e pergunte sobre sequências, desempenho financeiro, risco ou ideias de estratégia.</p><div className="mx-auto mt-5 grid max-w-2xl grid-cols-2 gap-2">{suggestions.map(item=><button key={item} onClick={()=>setPrompt(item)} className="rounded-md border border-line bg-canvas p-3 text-left text-[10px] text-muted hover:border-brand/40 hover:text-ink">{item}</button>)}</div></div></div>}{messages.map((item,index)=><div key={index} className={`flex ${item.role==='user'?'justify-end':'justify-start'}`}><div className={`max-w-[82%] whitespace-pre-wrap rounded-xl px-4 py-3 text-xs leading-5 ${item.role==='user'?'bg-brand text-white':'border border-line bg-elevated text-ink'}`}>{item.content}</div></div>)}{sending&&<div className="flex items-center gap-2 text-xs text-muted"><div className="loader h-4 w-4"/>Analisando os históricos...</div>}<div ref={chatEndRef}/></div>
        {audioUrl&&<div className="mx-4 mb-2 flex items-center gap-3 rounded-md border border-brand/25 bg-brand/5 p-2"><Volume2 size={15} className="text-blue-300"/><audio controls src={audioUrl} className="h-8 flex-1"/><span className="font-mono text-[10px] text-muted">{formatTime(recordingSeconds)}</span><button onClick={clearAudio} className="text-muted hover:text-danger"><Trash2 size={14}/></button></div>}<div className="border-t border-line p-4"><div className="flex items-end gap-2"><textarea rows={2} value={prompt} onChange={e=>setPrompt(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();void send()}}} placeholder="Pergunte sobre os resultados ou use o microfone..." className="max-h-32 min-h-[52px] flex-1 resize-none px-3 py-2.5 text-xs"/><Button onClick={recording?stopRecording:()=>void startRecording()} disabled={sending||Boolean(audioBlob)} title={recording?'Parar gravação':'Gravar áudio'} className={recording?'h-[52px] bg-danger text-white':'h-[52px] border-line bg-elevated text-muted'}>{recording?<><Square size={14}/>{formatTime(recordingSeconds)}</>:<Mic size={16}/>}</Button><Button onClick={()=>void send()} disabled={sending||(!prompt.trim()&&!audioBlob)||!(scope==='TERMINAL'?terminalId:platformId)} className="h-[52px] bg-brand px-5 text-white"><Send size={16}/></Button></div><div className="mt-2 flex items-center text-[9px] text-muted">Enter envia • Shift+Enter quebra a linha • áudio máximo de 2 minutos <span className="ml-auto">Os dados selecionados são enviados ao modelo configurado.</span></div></div></Card></div>
  </div>;
}

function Field({label,children}:{label:string;children:ReactNode}){return <label className="mt-3 block"><span className="label">{label}</span>{children}</label>}
function ScopeButton({active,onClick,children}:{active:boolean;onClick():void;children:ReactNode}){return <button onClick={onClick} className={`h-9 rounded-md border text-xs ${active?'border-brand/40 bg-brand/10 text-blue-300':'border-line bg-canvas text-muted'}`}>{children}</button>}
function formatTime(seconds:number){return `${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`}
async function blobToBase64(blob:Blob){const bytes=new Uint8Array(await blob.arrayBuffer());let binary='';const chunk=0x8000;for(let offset=0;offset<bytes.length;offset+=chunk)binary+=String.fromCharCode(...bytes.subarray(offset,offset+chunk));return btoa(binary)}
