import { useEffect, useRef, useState } from 'react';
import { Banknote, Bot, History, Minus, RotateCcw, X } from 'lucide-react';
import type { NormalizedRound, Platform } from '@aviator/shared';

type SlotNumber=1|2;
type SlotState={amount:string;cashout:string;pending:{stakeCents:number;cashout:number;placedAt:string}|null};
type SettledSlot={slot:SlotNumber;stakeCents:number;cashout:number;won:boolean;returnedCents:number;profitLossCents:number};
type SessionRow={id:string;multiplier:number;occurredAt:string;balanceCents:number;profitLossCents:number;settled:SettledSlot[]};
type SimulatorLaunch={platformId:string|null;terminalId:string|null;terminalName:string|null;bankrollCents:number};

const initialSlot=():SlotState=>({amount:'1.00',cashout:'10.00',pending:null});
const money=(cents:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(cents/100);
const multiplierTone=(value:number)=>value>=10?'text-fuchsia-300':value>=2?'text-blue-300':'text-cyan-300';

export function BetSimulatorWindow(){
  const query=new URLSearchParams(window.location.hash.split('?')[1]??'');
  const launchRef=useRef<SimulatorLaunch>({platformId:query.get('platformId'),terminalId:query.get('terminalId'),terminalName:query.get('terminalName'),bankrollCents:Math.max(100,Number(query.get('bankrollCents'))||10_000)});
  const[platforms,setPlatforms]=useState<Platform[]>([]);const[platformId,setPlatformIdState]=useState(launchRef.current.platformId??'');const platformIdRef=useRef(platformId);
  const[bankrollCents,setBankrollState]=useState(launchRef.current.bankrollCents);const bankrollRef=useRef(bankrollCents);const[bankrollDraft,setBankrollDraft]=useState((launchRef.current.bankrollCents/100).toFixed(2));
  const[slots,setSlotsState]=useState<[SlotState,SlotState]>([initialSlot(),initialSlot()]);const slotsRef=useRef(slots);
  const[rounds,setRounds]=useState<NormalizedRound[]>([]);const[session,setSession]=useState<SessionRow[]>([]);const[message,setMessage]=useState('Aguardando a próxima rodada real da plataforma.');const[lastLiveAt,setLastLiveAt]=useState<string|null>(null);const[calibrating,setCalibrating]=useState(false);const[connected,setConnected]=useState(false);const[testing,setTesting]=useState(false);
  const seenRounds=useRef(new Set<string>());
  const setBankroll=(value:number)=>{bankrollRef.current=value;setBankrollState(value)};
  const setSlots=(value:[SlotState,SlotState])=>{slotsRef.current=value;setSlotsState(value)};
  const setPlatform=(value:string)=>{platformIdRef.current=value;setPlatformIdState(value);seenRounds.current.clear();setSession([]);setSlots([initialSlot(),initialSlot()]);void loadRounds(value)};
  async function loadRounds(selected:string){if(!selected)return;const result=await window.aviator.getRecentRounds(selected,50);if(result.ok&&result.data){setRounds(result.data);for(const round of result.data)seenRounds.current.add(round.id);}}

  useEffect(()=>{document.title='Aviator Lab • Simulador de Plataforma';void window.aviator.bootstrap().then(result=>{if(!result.ok||!result.data)return;setPlatforms(result.data.platforms);const selected=platformIdRef.current||result.data.platforms[0]?.id||'';platformIdRef.current=selected;setPlatformIdState(selected);void loadRounds(selected)});const stopRound=window.aviator.onBetSimulatorRound(round=>applyRound(round));const autoConnectTimer=window.setTimeout(()=>{if(launchRef.current.terminalId)void connectBot()},400);const stopConfigure=window.aviator.onBetSimulatorConfigure(config=>{launchRef.current=config;setConnected(false);if(config.platformId&&config.platformId!==platformIdRef.current)setPlatform(config.platformId);else{setSession([]);setSlots([initialSlot(),initialSlot()])}setBankroll(config.bankrollCents);setBankrollDraft((config.bankrollCents/100).toFixed(2));setMessage(`Conectando automaticamente ao Terminal ${config.terminalName??'selecionado'}...`);window.setTimeout(()=>void connectBot(),300)});return()=>{window.clearTimeout(autoConnectTimer);stopRound();stopConfigure()}},[]);

  async function connectBot(){const terminalId=launchRef.current.terminalId;if(!terminalId){setConnected(false);setMessage('Abra o simulador pelo botão do Terminal para conectar o bot.');return}setCalibrating(true);try{const result=await window.aviator.calibrateBetSimulator(terminalId);if(!result.ok){setConnected(false);setMessage(result.error??'Não foi possível calibrar o bot.');return}setConnected(true);setMessage('Bot conectado e MOUSE ATIVO somente nesta janela. Ao fechar, ele será desativado automaticamente.')}finally{setCalibrating(false)}}
  async function testBot(){const terminalId=launchRef.current.terminalId;if(!terminalId){setMessage('Abra este simulador pelo Terminal antes do teste.');return}setTesting(true);try{const result=await window.aviator.testBetSimulator(terminalId);if(!result.ok){setMessage(result.error??'O teste físico falhou.');return}setConnected(true);setMessage('TESTE CONCLUÍDO: R$ 1,00 preenchido, saída 2,00x e Aposta 1 clicada.')}finally{setTesting(false)}}

  function applyRound(round:NormalizedRound){
    if(round.platformId!==platformIdRef.current||seenRounds.current.has(round.id))return;seenRounds.current.add(round.id);setRounds(current=>[round,...current].slice(0,50));if(round.deliveryMode!=='LIVE'){setMessage('Rodada histórica recebida • nenhuma aposta foi liquidada.');return}setLastLiveAt(new Date().toISOString());
    const active=slotsRef.current;const settled:SettledSlot[]=[];let returned=0;let stakes=0;
    active.forEach((slot,index)=>{if(!slot.pending)return;const won=round.multiplier>=slot.pending.cashout;const returnedCents=won?Math.round(slot.pending.stakeCents*slot.pending.cashout):0;returned+=returnedCents;stakes+=slot.pending.stakeCents;settled.push({slot:(index+1) as SlotNumber,stakeCents:slot.pending.stakeCents,cashout:slot.pending.cashout,won,returnedCents,profitLossCents:returnedCents-slot.pending.stakeCents})});
    const balance=bankrollRef.current+returned;setBankroll(balance);setSlots(active.map(slot=>({...slot,pending:null})) as [SlotState,SlotState]);const profit=returned-stakes;
    setSession(current=>[{id:round.id,multiplier:round.multiplier,occurredAt:round.occurredAt,balanceCents:balance,profitLossCents:profit,settled},...current].slice(0,200));setMessage(settled.length?`${settled.length} aposta(s) liquidada(s) em ${round.multiplier.toFixed(2)}x.`:`Rodada ${round.multiplier.toFixed(2)}x recebida • sem aposta.`);
  }

  function updateSlot(index:number,field:'amount'|'cashout',value:string){const next=slotsRef.current.map((slot,position)=>position===index?{...slot,[field]:value}:slot) as [SlotState,SlotState];setSlots(next)}
  function placeBet(index:number){const current=slotsRef.current[index];if(current.pending)return;const stakeCents=Math.round(Number(current.amount.replace(',','.'))*100);const cashout=Number(current.cashout.replace(',','.'));if(!Number.isInteger(stakeCents)||stakeCents<=0||!Number.isFinite(cashout)||cashout<=1){setMessage('Informe valor e saída válidos.');return}if(stakeCents>bankrollRef.current){setMessage('Saldo insuficiente para esta aposta.');return}const next=slotsRef.current.map((slot,position)=>position===index?{...slot,pending:{stakeCents,cashout,placedAt:new Date().toISOString()}}:slot) as [SlotState,SlotState];setBankroll(bankrollRef.current-stakeCents);setSlots(next);setMessage(`Aposta ${index+1} armada: ${money(stakeCents)} com saída em ${cashout.toFixed(2)}x.`)}
  function applyBankroll(){const cents=Math.round(Number(bankrollDraft.replace(',','.'))*100);if(!Number.isInteger(cents)||cents<=0){setMessage('Informe uma banca maior que zero.');return}if(slotsRef.current.some(slot=>slot.pending)){setMessage('Aguarde a liquidação das apostas antes de alterar a banca.');return}setBankroll(cents);setSession([]);setMessage(`Nova sessão iniciada com ${money(cents)}.`)}
  function resetSession(){if(slotsRef.current.some(slot=>slot.pending)){setMessage('Não é possível limpar enquanto existe aposta pendente.');return}setBankroll(launchRef.current.bankrollCents);setBankrollDraft((launchRef.current.bankrollCents/100).toFixed(2));setSession([]);setMessage('Sessão reiniciada.');}
  const latest=rounds[0];const selectedPlatform=platforms.find(item=>item.id===platformId);const totalProfit=session.reduce((total,item)=>total+item.profitLossCents,0);
  return <div className="flex h-screen min-h-[620px] flex-col overflow-hidden bg-[#070b10] text-slate-100">
    <header className="drag-region flex h-10 shrink-0 items-center border-b border-white/10 bg-[#090d13] pl-3"><Bot size={15} className="mr-2 text-rose-400"/><span className="text-[11px] font-extrabold tracking-[.16em]">AVIATOR LAB • SIMULADOR DE PLATAFORMA</span><span className="ml-3 rounded-full border border-emerald-400/25 bg-emerald-400/10 px-2 py-0.5 text-[8px] font-bold tracking-wider text-emerald-300">SEM DINHEIRO REAL</span><div className="no-drag ml-auto flex h-full"><button onClick={()=>void window.aviator.windowMinimize()} className="title-button"><Minus size={14}/></button><button onClick={()=>void window.aviator.windowClose()} className="title-button hover:bg-red-500/80"><X size={14}/></button></div></header>
    <section className="grid shrink-0 grid-cols-[1fr_165px_120px_140px_115px_38px] gap-2 border-b border-white/10 bg-[#0d131b] p-2">
      <label><span className="text-[8px] font-bold uppercase tracking-widest text-slate-500">Plataforma das rodadas</span><select value={platformId} onChange={event=>setPlatform(event.target.value)} className="mt-1 h-8 w-full">{platforms.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>
      <label><span className="text-[8px] font-bold uppercase tracking-widest text-slate-500">Banca da simulação (R$)</span><input value={bankrollDraft} onChange={event=>setBankrollDraft(event.target.value)} onKeyDown={event=>{if(event.key==='Enter')applyBankroll()}} className="mt-1 h-8 w-full font-mono"/></label>
      <button onClick={applyBankroll} className="mt-[18px] h-8 rounded-md bg-blue-600 text-[10px] font-bold hover:bg-blue-500"><Banknote size={12} className="mr-1 inline"/>APLICAR BANCA</button>
<button disabled={calibrating||!launchRef.current.terminalId} onClick={()=>void connectBot()} className={`mt-[18px] h-8 rounded-md border text-[10px] font-bold disabled:cursor-not-allowed disabled:opacity-40 ${connected?'animate-pulse border-emerald-300 bg-emerald-500/25 text-emerald-200 shadow-[0_0_16px_rgba(34,197,94,.45)]':'border-emerald-400/40 bg-emerald-400/10 text-emerald-300 hover:bg-emerald-400/20'}`}><Bot size={12} className="mr-1 inline"/>{calibrating?'CONECTANDO...':connected?'BOT CONECTADO':'CONECTAR E ATIVAR'}</button>
<button disabled={testing||calibrating||!launchRef.current.terminalId} onClick={()=>void testBot()} className="mt-[18px] h-8 rounded-md border border-amber-300/40 bg-amber-400/10 text-[10px] font-bold text-amber-200 hover:bg-amber-400/20 disabled:cursor-not-allowed disabled:opacity-40"><Banknote size={12} className="mr-1 inline"/>{testing?'TESTANDO...':'TESTAR R$ 1'}</button>
      <button title="Reiniciar sessão" onClick={resetSession} className="mt-[18px] grid h-8 place-items-center rounded-md border border-white/10 text-slate-400 hover:bg-white/5"><RotateCcw size={13}/></button>
    </section>
    <main className="grid min-h-0 flex-1 grid-rows-[34px_minmax(190px,1fr)_166px_minmax(115px,.65fr)] gap-1.5 p-1.5">
      <div className="flex items-center gap-2 overflow-hidden rounded-md border border-white/10 bg-[#0b1118] px-2"><span className="shrink-0 text-[8px] font-bold uppercase tracking-widest text-slate-500">Histórico</span>{rounds.slice(0,18).map(round=><span key={round.id} className={`shrink-0 font-mono text-[9px] font-bold ${multiplierTone(round.multiplier)}`}>{round.multiplier.toFixed(2)}x</span>)}<span className="ml-auto flex shrink-0 items-center gap-1 text-[8px] font-bold text-emerald-300"><span className={`h-1.5 w-1.5 rounded-full ${lastLiveAt?'animate-pulse bg-emerald-400':'bg-slate-600'}`}/>{lastLiveAt?'AO VIVO':'CONECTANDO'}</span></div>
      <div className="relative overflow-hidden rounded-xl border border-white/10 bg-[radial-gradient(circle_at_50%_100%,rgba(25,94,125,.34),transparent_42%),repeating-conic-gradient(from_268deg_at_0%_100%,rgba(36,63,81,.35)_0deg_4deg,transparent_4deg_10deg),#070b0f]">
        <svg className="absolute inset-x-0 bottom-0 h-[72%] w-full" preserveAspectRatio="none" viewBox="0 0 1000 300"><path d="M0 296 C170 292 260 276 350 242 C470 196 520 120 625 92 C730 62 820 60 1000 18 L1000 300 L0 300 Z" fill="rgba(190,0,47,.34)"/><path d="M0 296 C170 292 260 276 350 242 C470 196 520 120 625 92 C730 62 820 60 1000 18" fill="none" stroke="#ff174f" strokeWidth="5"/></svg>
        <div className="absolute inset-0 grid place-items-center"><div className="text-center"><div className="font-mono text-6xl font-black tracking-tight text-white drop-shadow-[0_0_20px_rgba(255,255,255,.18)]">{latest?`${latest.multiplier.toFixed(2)}x`:'—'}</div><div className="mt-2 text-[9px] font-bold uppercase tracking-[.22em] text-slate-400">{selectedPlatform?.name??'Selecione uma plataforma'}</div></div></div>
        <div className="absolute bottom-3 left-3 rounded-md border border-white/10 bg-black/35 px-3 py-1.5 font-mono text-[9px] text-slate-300">{message}</div><div className="absolute right-3 top-3 text-right"><div className="text-[8px] font-bold uppercase tracking-widest text-slate-500">Saldo disponível</div><div className="mt-1 font-mono text-xl font-black text-emerald-300">{money(bankrollCents)}</div><div className={`font-mono text-[9px] font-bold ${totalProfit>=0?'text-emerald-400':'text-red-400'}`}>Sessão {totalProfit>=0?'+':''}{money(totalProfit)}</div></div>
      </div>
      <div className="grid grid-cols-2 gap-1.5">{slots.map((slot,index)=><BetPanel key={index} index={index} slot={slot} bankrollCents={bankrollCents} onChange={updateSlot} onBet={placeBet}/>)}</div>
      <div className="min-h-0 overflow-hidden rounded-lg border border-white/10 bg-[#0b1118]"><div className="flex h-8 items-center border-b border-white/10 px-3"><History size={12} className="mr-2 text-blue-300"/><span className="text-[8px] font-bold uppercase tracking-widest text-slate-400">Liquidações da sessão</span><span className="ml-auto text-[8px] text-slate-600">A aposta clicada vale para a próxima rodada recebida</span></div><div className="h-[calc(100%-2rem)] overflow-y-auto"><table className="w-full table-fixed text-left text-[9px]"><thead className="sticky top-0 bg-[#101720] text-slate-500"><tr><th className="w-24 px-3 py-1.5">Hora</th><th className="w-20">Rodada</th><th>Apostas</th><th className="w-24">Resultado</th><th className="w-28">Saldo</th></tr></thead><tbody>{session.map(row=><tr key={row.id} className="border-t border-white/5"><td className="px-3 py-1.5 font-mono text-slate-500">{new Date(row.occurredAt).toLocaleTimeString('pt-BR')}</td><td className={`font-mono font-bold ${multiplierTone(row.multiplier)}`}>{row.multiplier.toFixed(2)}x</td><td className="truncate text-slate-300">{row.settled.length?row.settled.map(item=>`A${item.slot} ${money(item.stakeCents)} @ ${item.cashout.toFixed(2)}x`).join(' • '):'Sem aposta'}</td><td className={`font-mono font-bold ${row.profitLossCents>=0?'text-emerald-400':'text-red-400'}`}>{row.settled.length?`${row.profitLossCents>=0?'+':''}${money(row.profitLossCents)}`:'—'}</td><td className="font-mono text-slate-300">{money(row.balanceCents)}</td></tr>)}</tbody></table>{!session.length&&<div className="grid h-16 place-items-center text-[9px] text-slate-600">Aguardando rodadas ao vivo para iniciar o histórico financeiro.</div>}</div></div>
    </main>
  </div>;
}

function BetPanel({index,slot,bankrollCents,onChange,onBet}:{index:number;slot:SlotState;bankrollCents:number;onChange(index:number,field:'amount'|'cashout',value:string):void;onBet(index:number):void}){const number=index+1;return <section className={`grid grid-cols-[1fr_1fr_1.25fr] gap-2 rounded-xl border p-3 ${slot.pending?'border-amber-400/50 bg-amber-400/5':'border-white/10 bg-[#111821]'}`}><label><span className="text-[8px] font-bold uppercase tracking-widest text-slate-500">Valor da aposta {number}</span><input id={`sim-bet${number}-amount`} data-coordinate={`bet${number}.amount`} value={slot.amount} disabled={Boolean(slot.pending)} onChange={event=>onChange(index,'amount',event.target.value)} className="mt-1.5 h-10 w-full font-mono text-base font-black"/></label><label><span className="text-[8px] font-bold uppercase tracking-widest text-slate-500">Saída automática</span><input id={`sim-bet${number}-cashout`} data-coordinate={`bet${number}.cashout`} value={slot.cashout} disabled={Boolean(slot.pending)} onChange={event=>onChange(index,'cashout',event.target.value)} className="mt-1.5 h-10 w-full font-mono text-base font-black"/></label><button id={`sim-bet${number}-action`} data-coordinate={`bet${number}.action`} disabled={Boolean(slot.pending)||bankrollCents<=0} onClick={()=>onBet(index)} className={`mt-[18px] rounded-lg border text-sm font-black transition ${slot.pending?'cursor-default border-amber-300/40 bg-amber-400/15 text-amber-200':'border-emerald-300/50 bg-emerald-500 text-white shadow-[0_0_18px_rgba(34,197,94,.18)] hover:bg-emerald-400'}`}>{slot.pending?<><span className="block text-[9px] tracking-widest">APOSTA ARMADA</span>{money(slot.pending.stakeCents)} @ {slot.pending.cashout.toFixed(2)}x</>:<>Aposta {number}<span className="block font-mono text-xs">{money(Math.round((Number(slot.amount.replace(',','.'))||0)*100))}</span></>}</button></section>}
