import { Pencil, Plus, Search, Trash2, Workflow } from 'lucide-react';
import { useState, type FormEvent, type ReactNode } from 'react';
import type { TerminalControlRule } from '@aviator/shared';
import { Badge, Button, Card, Modal } from '@/components/ui';
import { useAppStore } from '@/store/app-store';

const metrics=[['currentLossStreak','Perdas consecutivas atuais'],['currentWinStreak','Ganhos consecutivos atuais'],['lastClosedLossStreak','Última sequência de perdas'],['lastClosedWinStreak','Última sequência de ganhos'],['lastCycleLossCount','LOSS no último ciclo de aposta'],['lastCycleWinCount','WIN no último ciclo de aposta'],['winRate','Taxa de ganhos (%)'],['bankroll','Saldo (R$)']] as const;
const operators=[['GTE','Maior ou igual a'],['GT','Maior que'],['EQ','Igual a'],['LTE','Menor ou igual a'],['LT','Menor que']] as const;

export function ControlRulesPage(){
  const store=useAppStore();const[editing,setEditing]=useState<TerminalControlRule|null|undefined>(undefined);const[query,setQuery]=useState('');const[dynamic,setDynamic]=useState(false);
  const rules=store.terminalControlRules.filter(rule=>`${rule.name} ${metricLabel(rule.metric)} ${rule.action}`.toLowerCase().includes(query.toLowerCase()));
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);const saved=await store.saveTerminalControlRule({id:editing?.id??null,name:form.get('name'),sortOrder:Number(form.get('sortOrder')),enabled:form.get('enabled')==='on',metric:form.get('metric'),operator:form.get('operator'),value:dynamic?0:Number(form.get('value')),referenceMetric:dynamic?form.get('referenceMetric'):null,action:form.get('action')});if(saved)setEditing(undefined);}
  const nextOrder=store.terminalControlRules.length?Math.max(...store.terminalControlRules.map(rule=>rule.sortOrder))+10:10;
  return <div className="p-5"><div className="mb-5 flex items-end justify-between"><div><h2 className="text-xl font-bold">Regras globais de controle</h2><p className="mt-1 text-xs text-muted">Crie gatilhos PLAY e PAUSE reutilizáveis e vincule vários deles em cada Terminal.</p></div><Button onClick={()=>{store.clearError();setDynamic(false);setEditing(null)}} className="bg-brand text-white"><Plus size={14}/>Nova regra global</Button></div>
    <Card className="mb-3 p-3"><div className="relative max-w-lg"><Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-muted"/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Buscar regra, indicador ou ação..." className="pl-9"/></div></Card>
    <div className="grid gap-3 xl:grid-cols-2">{rules.map(rule=>{const uses=store.terminals.filter(terminal=>terminal.controlPlayRuleIds.includes(rule.id)||terminal.controlPauseRuleIds.includes(rule.id));return <Card key={rule.id} className="p-4"><div className="flex items-start gap-3"><div className="grid h-9 w-9 place-items-center rounded-md bg-brand/10 text-blue-300"><Workflow size={17}/></div><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><h3 className="truncate text-sm font-semibold">{rule.name}</h3><Badge tone={rule.action==='PAUSE'?'warning':'success'}>{rule.action==='PAUSE'?'PAUSE':'PLAY'}</Badge><Badge tone={rule.enabled?'success':'neutral'}>{rule.enabled?'ATIVA':'INATIVA'}</Badge></div><div className="mt-2 text-[10px] text-muted">{metricLabel(rule.metric)} {operatorLabel(rule.operator)} <span className="font-mono text-ink">{rule.referenceMetric?metricLabel(rule.referenceMetric):rule.value}</span></div><div className="mt-1 text-[9px] text-muted">Vinculada a {uses.length} Terminal(is){uses.length?`: ${uses.map(item=>item.name).join(', ')}`:''}</div></div><button title="Editar" onClick={()=>{setDynamic(Boolean(rule.referenceMetric));setEditing(rule)}} className="grid h-8 w-8 place-items-center rounded-md border border-line text-muted hover:text-ink"><Pencil size={13}/></button><button title="Excluir" onClick={()=>{if(window.confirm(`Excluir ${rule.name}? Os vínculos também serão removidos.`))void store.deleteTerminalControlRule(rule.id)}} className="grid h-8 w-8 place-items-center rounded-md border border-line text-muted hover:text-danger"><Trash2 size={13}/></button></div></Card>})}</div>
    <Modal title={`${editing?'Editar':'Nova'} regra global`} open={editing!==undefined} onClose={()=>setEditing(undefined)}><form onSubmit={submit} className="grid grid-cols-2 gap-4 p-5"><Field label="Nome"><input name="name" defaultValue={editing?.name??'Novo gatilho global'} required/></Field><Field label="Ordem"><input name="sortOrder" type="number" defaultValue={editing?.sortOrder??nextOrder}/></Field><Field label="Tipo"><select name="action" defaultValue={editing?.action==='RESUME'?'PLAY':editing?.action??'PAUSE'}><option value="PLAY">PLAY — permitir iniciar/retomar</option><option value="PAUSE">PAUSE — interromper</option></select></Field><Field label="Indicador"><select name="metric" defaultValue={editing?.metric??'currentLossStreak'}>{metrics.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></Field><Field label="Comparação"><select name="operator" defaultValue={editing?.operator??'GTE'}>{operators.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></Field><Field label="Tipo de valor"><select value={dynamic?'DYNAMIC':'FIXED'} onChange={event=>setDynamic(event.target.value==='DYNAMIC')}><option value="FIXED">Valor fixo</option><option value="DYNAMIC">Outro indicador</option></select></Field>{dynamic?<Field label="Indicador comparado"><select name="referenceMetric" defaultValue={editing?.referenceMetric??'lastClosedLossStreak'}>{metrics.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></Field>:<Field label="Valor"><input name="value" type="number" step="0.01" defaultValue={editing?.value??1}/></Field>}<label className="col-span-2 flex items-center gap-2 text-xs text-muted"><input name="enabled" type="checkbox" defaultChecked={editing?.enabled??true}/>Regra disponível e ativa</label>{store.error&&<div className="col-span-2 rounded-md border border-danger/25 bg-danger/10 p-3 text-xs text-red-200">{store.error}</div>}<div className="col-span-2 flex justify-end gap-2"><Button type="button" onClick={()=>setEditing(undefined)} className="border-line bg-panel text-muted">Cancelar</Button><Button className="bg-brand text-white">Salvar regra</Button></div></form></Modal>
  </div>;
}
function Field({label,children}:{label:string;children:ReactNode}){return <label><span className="label">{label}</span><div className="form-field mt-1.5">{children}</div></label>}
function metricLabel(metric:TerminalControlRule['metric']){return metrics.find(item=>item[0]===metric)?.[1]??metric}
function operatorLabel(operator:TerminalControlRule['operator']){return operators.find(item=>item[0]===operator)?.[1].toLowerCase()??operator}
