import { useEffect, useMemo, useState } from 'react';
import { Activity, Bot, Database, Pause, Radio, ShieldCheck, SquareTerminal, Zap } from 'lucide-react';
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import type { NormalizedRound } from '@aviator/shared';
import { Badge, Card } from '@/components/ui';
import { money, percent } from '@/lib/utils';
import { useAppStore } from '@/store/app-store';

export function DashboardPage(){
  const{terminals,platforms,collectors,terminalHistories,eventBus}=useAppStore();const[platformId,setPlatformId]=useState('ALL');const[terminalId,setTerminalId]=useState('ALL');const[roundCount,setRoundCount]=useState<12|24|40>(12);const[rounds,setRounds]=useState<NormalizedRound[]>([]);
  const visible=useMemo(()=>terminals.filter(item=>(platformId==='ALL'||item.platformId===platformId)&&(terminalId==='ALL'||item.id===terminalId)),[terminals,platformId,terminalId]);
  useEffect(()=>{if(terminalId!=='ALL'&&!terminals.some(item=>item.id===terminalId&&(platformId==='ALL'||item.platformId===platformId)))setTerminalId('ALL')},[platformId,terminalId,terminals]);
  useEffect(()=>{let active=true;void window.aviator.getRecentRounds(platformId==='ALL'?null:platformId,50).then(result=>{if(active&&result.ok&&result.data)setRounds(result.data)});return()=>{active=false}},[platformId,eventBus.publishedEvents]);
  const total=visible.reduce((sum,item)=>sum+item.currentBankrollCents,0),wins=visible.reduce((sum,item)=>sum+item.gameWins,0),losses=visible.reduce((sum,item)=>sum+item.gameLosses,0);
  const chart=useMemo(()=>{const terminal=terminalId==='ALL'?visible[0]:visible.find(item=>item.id===terminalId);if(!terminal)return[];return[{t:'Inicial',v:terminal.initialBankrollCents/100},...(terminalHistories[terminal.id]??[]).filter(item=>item.execution).map((item,index)=>({t:String(index+1),v:item.execution!.bankrollAfterCents/100}))]},[visible,terminalId,terminalHistories]);
  const selectedPlatform=platformId==='ALL'?null:platforms.find(item=>item.id===platformId);const collector=collectors.find(item=>item.platformId===(selectedPlatform?.id??platforms[0]?.id));
  return <div className="p-5"><div className="mb-5 flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-xl font-bold">Visão geral</h2><p className="mt-1 text-xs text-muted">Escolha a plataforma, o Terminal e a quantidade de rodadas exibidas.</p></div><div className="flex items-end gap-2"><Selector label="Plataforma" value={platformId} onChange={setPlatformId} options={[{id:'ALL',name:'Todas as plataformas'},...platforms]}/><Selector label="Terminal" value={terminalId} onChange={setTerminalId} options={[{id:'ALL',name:'Todos os Terminais'},...terminals.filter(item=>platformId==='ALL'||item.platformId===platformId)]}/><label><span className="label">Rodadas recentes</span><select className="mt-1 w-32" value={roundCount} onChange={event=>setRoundCount(Number(event.target.value) as 12|24|40)}><option value="12">12 rodadas</option><option value="24">24 rodadas</option><option value="40">40 rodadas</option></select></label></div></div>
    <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><Metric icon={SquareTerminal} label="Terminais" value={String(visible.length)} detail={`${visible.filter(item=>!item.paused).length} em execução`} tone="blue"/><Metric icon={Database} label="Coletores" value={String(collectors.filter(item=>item.status==='ONLINE').length)} detail={`${collectors.length} configurados`} tone="green"/><Metric icon={Activity} label="Taxa de WIN" value={percent(wins+losses?wins/(wins+losses)*100:0)} detail={`${wins} W • ${losses} L`} tone="violet"/><Metric icon={ShieldCheck} label="Banca selecionada" value={money(total)} detail="Isolada por Terminal" tone="amber"/></div>
    <div className="mt-3 grid gap-3 xl:grid-cols-[1.55fr_.85fr]"><Card className="min-h-[360px] p-4"><div className="mb-4"><div className="label">Curva de saldo {terminalId==='ALL'?'— primeiro Terminal do filtro':''}</div><div className="mt-1 text-lg font-bold">{chart.length?money(Math.round(chart.at(-1)!.v*100)):money(0)}</div></div><div className="h-[270px]">{chart.length?<ResponsiveContainer width="100%" height="100%"><AreaChart data={chart}><CartesianGrid stroke="#222a34" strokeDasharray="3 3" vertical={false}/><XAxis dataKey="t" stroke="#66717e" fontSize={10}/><YAxis stroke="#66717e" fontSize={10}/><Tooltip contentStyle={{background:'#161b22',border:'1px solid #2d333b',fontSize:11}}/><Area type="monotone" dataKey="v" stroke="#60a5fa" fill="#3b82f633"/></AreaChart></ResponsiveContainer>:<div className="grid h-full place-items-center text-xs text-muted">Nenhum Terminal corresponde ao filtro.</div>}</div></Card><Card className="overflow-hidden"><div className="flex items-center justify-between border-b border-line px-4 py-3"><div><div className="label">Rodadas recentes</div><div className="mt-1 text-xs text-muted">{selectedPlatform?.name??'Todas as plataformas'} • TipMiner</div></div><Radio size={15} className={collectors.some(item=>item.status==='ONLINE')?'text-success':'text-muted'}/></div><div className="grid max-h-[270px] grid-cols-4 gap-2 overflow-y-auto p-4">{rounds.slice(0,roundCount).map(round=><div key={`${round.platformId}-${round.id}`} title={new Date(round.occurredAt).toLocaleString('pt-BR')} className={`rounded-md border px-2 py-2 text-center font-mono text-[11px] font-bold ${round.multiplier>=2?'border-purple-500/30 bg-purple-500/10 text-purple-300':round.multiplier<1.35?'border-danger/25 bg-danger/10 text-red-300':'border-blue-500/25 bg-blue-500/10 text-blue-300'}`}>{round.multiplier.toFixed(2)}x</div>)}</div><div className="mx-4 mb-4 rounded-md border border-line bg-canvas p-3 text-[10px] text-muted"><div className="flex items-center justify-between"><span className="font-semibold text-ink">{selectedPlatform?.name??'Visão consolidada'}</span><Badge tone={collector?.status==='ONLINE'?'success':collector?.status==='DEGRADED'?'warning':'neutral'}>{collector?.status??'AGUARDANDO'}</Badge></div></div></Card></div>
    <Card className="mt-3 overflow-hidden"><div className="border-b border-line px-4 py-3"><div className="label">Terminais do filtro</div></div><div className="divide-y divide-line">{visible.map(terminal=>{const platform=platforms.find(item=>item.id===terminal.platformId);const rate=terminal.gameWins+terminal.gameLosses?terminal.gameWins/(terminal.gameWins+terminal.gameLosses)*100:0;return <div key={terminal.id} className="grid grid-cols-[1.3fr_.8fr_.8fr_.8fr_auto] items-center gap-4 px-4 py-3"><div className="flex items-center gap-3"><div className={`grid h-8 w-8 place-items-center rounded-md ${terminal.paused?'bg-warning/10 text-warning':'bg-success/10 text-success'}`}>{terminal.paused?<Pause size={15}/>:<Zap size={15}/>}</div><span className="text-xs font-semibold">{terminal.name}</span></div><Datum label="Plataforma" value={platform?.name??'—'}/><Datum label="Taxa de WIN" value={percent(rate)}/><Datum label="Saldo" value={money(terminal.currentBankrollCents)}/><Badge tone={terminal.paused?'warning':'success'}>{terminal.paused?'Pausado':'Executando'}</Badge></div>})}</div></Card>
  </div>;
}
function Selector({label,value,onChange,options}:{label:string;value:string;onChange(value:string):void;options:Array<{id:string;name:string}>}){return <label><span className="label">{label}</span><select className="mt-1 w-52" value={value} onChange={event=>onChange(event.target.value)}>{options.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>}
function Datum({label,value}:{label:string;value:string}){return <div><div className="label">{label}</div><div className="mt-1 font-mono text-[11px]">{value}</div></div>}
function Metric({icon:Icon,label,value,detail,tone}:{icon:typeof Bot;label:string;value:string;detail:string;tone:string}){const colors:Record<string,string>={blue:'bg-brand/10 text-blue-300',green:'bg-success/10 text-success',violet:'bg-purple-500/10 text-purple-300',amber:'bg-warning/10 text-warning'};return <Card className="p-4"><div className="flex justify-between"><div><div className="label">{label}</div><div className="mt-2 font-mono text-2xl font-bold">{value}</div><div className="mt-1 text-[10px] text-muted">{detail}</div></div><div className={`grid h-9 w-9 place-items-center rounded-lg ${colors[tone]}`}><Icon size={18}/></div></div></Card>}
