import { useEffect, useState } from 'react';
import { Activity, Clock3, Database, RefreshCw, Radio, ServerCrash } from 'lucide-react';
import type { NormalizedRound } from '@aviator/shared';
import { Badge, Button, Card } from '@/components/ui';
import { useAppStore } from '@/store/app-store';

type RoundLimit=50|100|250|500;
export function LiveMonitorPage() {
  const { collectors, platforms, syncCollectorNow, eventBus, terminals } = useAppStore();
  const[platformId,setPlatformId]=useState<string>('ALL');const[limit,setLimit]=useState<RoundLimit>(50);const[rounds,setRounds]=useState<NormalizedRound[]>([]);const[loading,setLoading]=useState(false);
  useEffect(()=>{let active=true;setLoading(true);void window.aviator.getRecentRounds(platformId==='ALL'?null:platformId,limit).then(result=>{if(active&&result.ok&&result.data)setRounds(result.data)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[platformId,limit,eventBus.publishedEvents]);
  return <div className="p-5"><div className="mb-5 flex items-end justify-between"><div><h2 className="text-xl font-bold">Monitor ao vivo</h2><p className="mt-1 text-xs text-muted">Polling sequencial, deduplicação e classificação de entrega em tempo real.</p></div><div className="flex items-center gap-2"><span className="h-2 w-2 animate-pulse rounded-full bg-success"/><span className="font-mono text-[10px] text-muted">ATUALIZAÇÃO AUTOMÁTICA</span></div></div>
    <Card className="mb-3 grid grid-cols-4 divide-x divide-line overflow-hidden"><Datum label="Coletores" value={String(collectors.length)} icon={Database}/><Datum label="Terminais inscritos" value={String(terminals.filter(t=>t.enabled&&!t.paused).length)} icon={Radio}/><Datum label="Eventos publicados" value={String(eventBus.publishedEvents)} icon={Activity}/><Datum label="Entregas aos Terminais" value={String(eventBus.deliveredEvents)} icon={RefreshCw}/></Card>
    <div className="mb-3 grid gap-3 md:grid-cols-3">{collectors.map(c=>{const p=platforms.find(p=>p.id===c.platformId);const subscribers=eventBus.subscribersByPlatform[c.platformId]??0;return <Card key={c.platformId} className="p-4"><div className="flex items-center justify-between"><div className="flex items-center gap-3"><div className={`grid h-9 w-9 place-items-center rounded-lg ${c.status==='ONLINE'?'bg-success/10 text-success':c.status==='DEGRADED'?'bg-warning/10 text-warning':'bg-danger/10 text-danger'}`}>{c.status==='OFFLINE'?<ServerCrash size={17}/>:<Radio size={17}/>}</div><div><div className="text-xs font-semibold">{p?.name}</div><div className="font-mono text-[9px] text-muted">{p?.pollIntervalMs} ms • {subscribers} Terminais</div></div></div><Badge tone={c.status==='ONLINE'?'success':c.status==='DEGRADED'?'warning':'danger'}>{c.status}</Badge></div><div className="mt-4 grid grid-cols-2 gap-3"><Datum label="Rodadas" value={String(c.persistedRounds)} icon={Database}/><Datum label="Falhas" value={String(c.consecutiveFailures)} icon={Activity}/></div><div className="mt-3 min-h-8 text-[10px] text-muted">{c.lastError??(c.lastSuccessAt?`Sucesso às ${new Date(c.lastSuccessAt).toLocaleTimeString('pt-BR')}`:'Sincronizando...')}</div><Button onClick={()=>void syncCollectorNow(c.platformId)} disabled={c.polling} className="mt-2 w-full border-line bg-elevated text-muted hover:text-ink"><RefreshCw size={13} className={c.polling?'animate-spin':''}/> Sincronizar agora</Button></Card>})}</div>
    <Card className="overflow-hidden"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-line px-4 py-3"><div><div className="label">Histórico persistido</div><div className="mt-1 text-xs text-muted">Mais recentes primeiro • retenção de 10.000 por plataforma</div></div><div className="flex items-center gap-2"><select className="w-56" value={platformId} onChange={event=>setPlatformId(event.target.value)}><option value="ALL">Todas as casas de aposta</option>{platforms.map(platform=><option key={platform.id} value={platform.id}>{platform.name}</option>)}</select><select className="w-36" value={limit} onChange={event=>setLimit(Number(event.target.value) as RoundLimit)}>{[50,100,250,500].map(value=><option key={value} value={value}>{value} rodadas</option>)}</select><span className="min-w-28 text-right font-mono text-[10px] text-muted">{loading?'CARREGANDO...':`${rounds.length} EXIBIDAS`}</span></div></div><div className="grid grid-cols-[.7fr_.9fr_.8fr_.8fr_1fr] border-b border-line bg-elevated/50 px-4 py-2 text-[9px] font-bold uppercase tracking-wider text-muted"><span>Multiplicador</span><span>Entrega</span><span>External ID</span><span>Casa de aposta</span><span>Horário</span></div><div className="max-h-[560px] divide-y divide-line overflow-y-auto">{rounds.map(r=>{const p=platforms.find(p=>p.id===r.platformId);return <div key={`${r.platformId}-${r.id}`} className="grid grid-cols-[.7fr_.9fr_.8fr_.8fr_1fr] items-center px-4 py-2.5 text-[11px] hover:bg-elevated/40"><span className={`font-mono font-bold ${r.multiplier>=2?'text-purple-300':r.multiplier<1.35?'text-red-300':'text-blue-300'}`}>{r.multiplier.toFixed(2)}x</span><Badge tone={r.deliveryMode==='LIVE'?'success':'neutral'}>{r.deliveryMode}</Badge><span className="font-mono text-muted">{r.externalId??'fingerprint'}</span><span>{p?.name??'—'}</span><span className="flex items-center gap-1.5 font-mono text-muted"><Clock3 size={11}/>{new Date(r.occurredAt).toLocaleString('pt-BR')}</span></div>})}</div></Card>
  </div>;
}
function Datum({label,value,icon:Icon}:{label:string;value:string;icon:typeof Activity}) { return <div className="rounded-md border border-line bg-canvas p-2"><div className="flex items-center gap-1.5 text-[9px] uppercase tracking-wider text-muted"><Icon size={11}/>{label}</div><div className="mt-1 font-mono text-sm font-semibold">{value}</div></div>; }
