import { useEffect, useState } from 'react';
import { ChevronLeft, ChevronRight, Gauge, Pause, Play, RotateCcw } from 'lucide-react';
import type { BacktestRun } from '@aviator/shared';
import { Badge, Button, Card } from '@/components/ui';
import { useAppStore } from '@/store/app-store';

export function ReplayPage() {
  const { platforms, gameStrategies, betStrategies, betPlans } = useAppStore();
  const [run, setRun] = useState<BacktestRun | null>(null); const [index,setIndex]=useState(0); const [playing,setPlaying]=useState(false); const [speed,setSpeed]=useState(1); const [error,setError]=useState<string|null>(null);
  useEffect(()=>{ if(!playing||!run) return; const timer=window.setInterval(()=>setIndex(current=>{if(current>=run.trace.length-1){setPlaying(false);return current;}return current+1;}),Math.max(30,700/speed)); return()=>window.clearInterval(timer); },[playing,run,speed]);
  const current=run?.trace[index];
  async function load(){ setError(null);const result=await window.aviator.runBacktest({platformId:platforms[0]?.id,gameStrategyId:gameStrategies[0]?.id,betStrategyId:betStrategies[0]?.id,betPlanId:betPlans[0]?.id,initialBankrollCents:100000,limit:2000});if(result.ok&&result.data){setRun(result.data);setIndex(0);setPlaying(false);}else setError(result.error??'Falha ao preparar o replay.'); }
  return <div className="p-5"><div className="mb-5 flex items-end justify-between"><div><h2 className="text-xl font-bold">Replay determinístico</h2><p className="mt-1 text-xs text-muted">Reproduz rodada a rodada o mesmo rastreamento gerado pelo motor de simulação.</p></div><Button onClick={()=>void load()} className="bg-brand text-white"><RotateCcw size={14}/>Carregar histórico</Button></div>{error&&<div className="mb-3 rounded-md border border-danger/30 bg-danger/10 p-3 text-xs text-red-200">{error}</div>}
    {!current||!run?<Card className="grid min-h-[430px] place-items-center text-center"><div><Gauge className="mx-auto text-muted" size={38}/><p className="mt-3 text-xs text-muted">Carregue o histórico para iniciar o replay.</p></div></Card>:<><Card className="mb-3 p-5"><div className="flex items-center justify-between"><div><div className="font-mono text-4xl font-black text-blue-300">{current.multiplier.toFixed(2)}x</div><div className="mt-1 font-mono text-[10px] text-muted">{new Date(current.occurredAt).toLocaleString('pt-BR')} • rodada {index+1}/{run.trace.length}</div></div><div className="flex gap-2"><Badge tone={current.gameResult==='WIN'?'success':current.gameResult==='LOSS'?'danger':'neutral'}>{current.gameResult??current.annotationRole}</Badge>{current.stageLabel&&<Badge tone={current.stageResult==='WIN'?'success':current.stageResult==='LOSS'?'danger':'warning'}>{current.stageLabel} • {current.stageResult==='TIE'?'EMPATE':current.stageResult}</Badge>}</div></div><div className="mt-5 h-2 overflow-hidden rounded-full bg-elevated"><div className="h-full bg-brand transition-all" style={{width:`${(index+1)/run.trace.length*100}%`}}/></div><input aria-label="Posição do replay" className="mt-3 w-full accent-blue-500" type="range" min={0} max={run.trace.length-1} value={index} onChange={e=>{setPlaying(false);setIndex(Number(e.target.value));}}/></Card>
      <div className="mb-3 grid grid-cols-2 gap-3 xl:grid-cols-5"><Datum label="Estado" value={current.strategyState}/><Datum label="Anotação" value={current.annotationRole}/><Datum label="Decisão" value={current.decisionAction??'—'}/><Datum label="Etapa" value={current.stageLabel??'—'}/><Datum label="Banca" value={(current.bankrollCents/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}/></div>
      <Card className="flex items-center justify-center gap-2 p-4"><Button onClick={()=>setIndex(0)} className="border-line bg-elevated"><RotateCcw size={14}/></Button><Button onClick={()=>setIndex(Math.max(0,index-1))} className="border-line bg-elevated"><ChevronLeft size={16}/></Button><Button onClick={()=>setPlaying(!playing)} className="w-28 bg-brand text-white">{playing?<Pause size={15}/>:<Play size={15}/>} {playing?'Pausar':'Reproduzir'}</Button><Button onClick={()=>setIndex(Math.min(run.trace.length-1,index+1))} className="border-line bg-elevated"><ChevronRight size={16}/></Button>{[1,2,10,20].map(value=><button key={value} onClick={()=>setSpeed(value)} className={`h-8 rounded-md px-3 font-mono text-[10px] ${speed===value?'bg-brand text-white':'bg-elevated text-muted'}`}>{value}x</button>)}</Card></>}
  </div>;
}
function Datum({label,value}:{label:string;value:string}){return <Card className="p-3"><div className="label">{label}</div><div className="mt-2 truncate font-mono text-xs font-bold">{value}</div></Card>}
