import { useEffect, useState } from 'react';
import { ArchiveRestore, CheckCircle2, CircleDot, DatabaseBackup, Download, MonitorUp, RefreshCw, RotateCw, ShieldCheck, Upload } from 'lucide-react';
import type { PerformanceBenchmarkResult, RecoverySnapshot, RoundArchiveStatus, SystemDiagnostics } from '@aviator/shared';
import { Badge, Button, Card } from '@/components/ui';

export function SettingsPage() {
  const [diagnostics, setDiagnostics] = useState<SystemDiagnostics | null>(null);
  const [archive,setArchive]=useState<RoundArchiveStatus|null>(null);
  const [snapshots,setSnapshots]=useState<RecoverySnapshot[]>([]);
  const [benchmark,setBenchmark]=useState<PerformanceBenchmarkResult[]>([]);const[benchmarking,setBenchmarking]=useState(false);
  const [message, setMessage] = useState<string | null>(null);
  const [restartRequired, setRestartRequired] = useState(false);
  const [interfaceScale,setInterfaceScale]=useState(1);
  const[terminalHistoryDisplayMax,setTerminalHistoryDisplayMax]=useState(200);
  async function load() { const [result,recovery,scale,archiveResult,dotLimit]=await Promise.all([window.aviator.getSystemDiagnostics(),window.aviator.listRecoverySnapshots(),window.aviator.getInterfaceScale(),window.aviator.getRoundArchiveStatus(),window.aviator.getTerminalHistoryDisplayMax()]); if(result.ok&&result.data)setDiagnostics(result.data);if(recovery.ok&&recovery.data)setSnapshots(recovery.data);if(scale.ok&&scale.data)setInterfaceScale(scale.data);if(archiveResult.ok&&archiveResult.data)setArchive(archiveResult.data);if(dotLimit.ok&&dotLimit.data)setTerminalHistoryDisplayMax(dotLimit.data); }
  useEffect(()=>{void load()},[]);
  async function exportWorkspace(){const result=await window.aviator.exportWorkspace();if(result.ok&&result.data)setMessage(`Workspace exportado para ${result.data}`);}
  async function importWorkspace(){if(!window.confirm('A importação mesclará configurações com o workspace atual e criará um snapshot de recuperação. Continuar?'))return;const result=await window.aviator.importWorkspace();if(result.ok&&result.data){setMessage('Importação concluída. Reinicie para reconstruir todos os runtimes.');setRestartRequired(true);void load();}else if(!result.ok)setMessage(result.error??'Falha ao importar.');}
  async function restore(id:string){if(!window.confirm('Restaurar este snapshot? O estado atual também será preservado em um novo snapshot.'))return;const result=await window.aviator.restoreRecoverySnapshot(id);if(result.ok){setMessage('Snapshot restaurado. Reinicie para reconstruir os Terminais com segurança.');setRestartRequired(true);void load();}else setMessage(result.error??'Falha ao restaurar snapshot.');}
  async function runBenchmark(){setBenchmarking(true);const result=await window.aviator.runPerformanceBenchmark();setBenchmarking(false);if(result.ok&&result.data)setBenchmark(result.data);else setMessage(result.error??'Falha no benchmark.');}
  async function changeInterfaceScale(scale:number){const result=await window.aviator.setInterfaceScale(scale);if(result.ok&&result.data){setInterfaceScale(result.data);setMessage(`Tamanho da interface ajustado para ${Math.round(result.data*100)}%.`);}else setMessage(result.error??'Não foi possível alterar o tamanho da interface.');}
  async function changeTerminalHistoryDisplayMax(value:number){const result=await window.aviator.setTerminalHistoryDisplayMax(value);if(result.ok&&result.data){setTerminalHistoryDisplayMax(result.data);setMessage(`Limite global ajustado para ${result.data} bolinhas por Terminal.`);}else setMessage(result.error??'Não foi possível alterar o limite de bolinhas.');}
  async function configureArchive(mode:'PUBLISHER'|'SUBSCRIBER'){const result=await window.aviator.configureRoundArchive(mode);if(result.ok&&result.data){setArchive(result.data);setMessage(mode==='PUBLISHER'?'Pasta compartilhada configurada. Snapshot publicado.':'Pasta compartilhada configurada para receber atualizações.');}else setMessage(result.error??'Falha ao configurar o histórico.');}
  async function publishArchive(){const result=await window.aviator.publishRoundArchive();if(result.ok&&result.data){setArchive(result.data);setMessage('Snapshot histórico publicado com integridade SHA-256.');}else setMessage(result.error??'Falha ao publicar o histórico.');}
  async function importArchive(){const result=await window.aviator.importRoundArchive();if(result.ok&&result.data){setArchive(result.data.status);setMessage(`${result.data.inserted.toLocaleString('pt-BR')} rodadas novas importadas.`);}else setMessage(result.error??'Falha ao importar o histórico.');}
  async function toggleBackground(){const result=await window.aviator.setBackgroundCollectorEnabled(!archive?.backgroundEnabled);if(result.ok&&result.data)setArchive(result.data);else setMessage(result.error??'Falha ao alterar o coletor em segundo plano.');}
  return <div className="p-5"><div className="mb-5 flex items-end justify-between"><div><h2 className="text-xl font-bold">Configurações e recuperação</h2><p className="mt-1 text-xs text-muted">Diagnóstico local, backup portátil e recuperação segura do workspace.</p></div><Button onClick={()=>void load()} className="border-line bg-panel text-muted"><RefreshCw size={13}/>Atualizar diagnóstico</Button></div>
    {message&&<div className="mb-3 rounded-md border border-brand/25 bg-brand/10 p-3 text-xs text-blue-100">{message}</div>}
    <Card className="mb-3 p-5"><div className="flex items-start gap-3"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-lg bg-brand/10 text-blue-300"><MonitorUp size={19}/></div><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-4"><div><h3 className="text-sm font-semibold">Tamanho da interface</h3><p className="mt-1 text-[10px] text-muted">Ajuste textos, menus, cartões e controles. A preferência fica salva para as próximas execuções.</p></div><Badge tone="brand">{Math.round(interfaceScale*100)}%</Badge></div><div className="mt-4 grid grid-cols-5 gap-2">{[0.8,0.9,1,1.1,1.25].map(scale=><button type="button" key={scale} onClick={()=>void changeInterfaceScale(scale)} className={`h-10 rounded-md border text-xs font-semibold transition ${interfaceScale===scale?'border-brand bg-brand/15 text-blue-300 ring-1 ring-brand/20':'border-line bg-canvas text-muted hover:border-brand/40 hover:text-ink'}`}>{Math.round(scale*100)}%</button>)}</div><div className="mt-3 flex items-center justify-between text-[10px] text-muted"><span>80% exibe mais conteúdo; 125% aumenta a leitura.</span><button type="button" onClick={()=>void changeInterfaceScale(1)} disabled={interfaceScale===1} className="font-semibold text-blue-300 hover:underline disabled:cursor-default disabled:text-muted disabled:no-underline">Restaurar 100%</button></div></div></div></Card>
    <Card className="mb-3 p-5"><div className="flex items-start gap-3"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-lg bg-brand/10 text-blue-300"><CircleDot size={19}/></div><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-4"><div><h3 className="text-sm font-semibold">Bolinhas do histórico nos Terminais</h3><p className="mt-1 text-[10px] text-muted">Define o máximo global. Cada Terminal poderá escolher uma quantidade igual ou menor em sua própria configuração.</p></div><Badge tone="brand">ATÉ {terminalHistoryDisplayMax}</Badge></div><div className="mt-4 grid grid-cols-7 gap-2">{[25,50,100,200,300,400,500].map(value=><button type="button" key={value} onClick={()=>void changeTerminalHistoryDisplayMax(value)} className={`h-10 rounded-md border text-xs font-semibold transition ${terminalHistoryDisplayMax===value?'border-brand bg-brand/15 text-blue-300 ring-1 ring-brand/20':'border-line bg-canvas text-muted hover:border-brand/40 hover:text-ink'}`}>{value}</button>)}</div><p className="mt-3 text-[10px] text-muted">A alteração reduz imediatamente a exibição; o histórico completo permanece salvo no banco de dados.</p></div></div></Card>
    <Card className="mb-3 p-5"><div className="flex items-start justify-between gap-4"><div><div className="flex items-center gap-2"><DatabaseBackup size={18} className="text-blue-300"/><h3 className="text-sm font-semibold">Coletor histórico independente</h3><Badge tone={archive?.backgroundEnabled?'success':'warning'}>{archive?.backgroundEnabled?'SEGUNDO PLANO':'SOMENTE COM O APP'}</Badge></div><p className="mt-2 text-[10px] text-muted">SQLite separado • até 300.000 rodadas por plataforma • {archive?.totalRounds.toLocaleString('pt-BR')??0} registros armazenados.</p><p className="mt-1 max-w-3xl truncate font-mono text-[9px] text-muted">{archive?.databasePath??'Carregando banco histórico...'}</p></div><Button onClick={()=>void toggleBackground()} className="border-line bg-elevated text-ink">{archive?.backgroundEnabled?'Desativar segundo plano':'Ativar segundo plano'}</Button></div><div className="mt-4 grid grid-cols-4 gap-2"><Button onClick={()=>void configureArchive('PUBLISHER')} className="bg-brand text-white"><Upload size={13}/>Configurar coletor central</Button><Button onClick={()=>void configureArchive('SUBSCRIBER')} className="border-line bg-elevated text-ink"><Download size={13}/>Conectar como usuário</Button><Button onClick={()=>void publishArchive()} disabled={archive?.syncMode!=='PUBLISHER'} className="border-line bg-elevated text-ink"><Upload size={13}/>Publicar agora</Button><Button onClick={()=>void importArchive()} disabled={!archive?.syncDirectory} className="border-line bg-elevated text-ink"><Download size={13}/>Buscar atualizações</Button></div><div className="mt-3 flex items-center gap-4 text-[9px] text-muted"><span>Modo: {archive?.syncMode==='PUBLISHER'?'coletor central':archive?.syncMode==='SUBSCRIBER'?'usuário':'não configurado'}</span><span className="min-w-0 truncate">Pasta: {archive?.syncDirectory??'selecione uma pasta local sincronizada pelo Google Drive'}</span>{archive?.lastPublishedAt&&<span>Publicado: {new Date(archive.lastPublishedAt).toLocaleString('pt-BR')}</span>}</div>{archive?.lastError&&<div className="mt-3 rounded-md border border-danger/25 bg-danger/10 p-2 text-[10px] text-red-200">{archive.lastError}</div>}</Card>
    <div className="mb-3 grid grid-cols-3 gap-3"><Card className="p-4"><div className="flex items-center justify-between"><div><div className="label">Integridade SQLite</div><div className="mt-2 font-mono text-lg font-bold">{diagnostics?.databaseIntegrity??'...'}</div></div><Badge tone={diagnostics?.databaseIntegrity==='ok'?'success':'warning'}>{diagnostics?.databaseIntegrity==='ok'?'SAUDÁVEL':'VERIFICANDO'}</Badge></div></Card><Metric label="Rodadas persistidas" value={diagnostics?.rounds}/><Metric label="Eventos auditados" value={diagnostics?.eventLogs}/></div>
    <div className="grid gap-3 xl:grid-cols-2"><Card className="p-5"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-lg bg-brand/10 text-blue-300"><DatabaseBackup size={19}/></div><div><h3 className="text-sm font-semibold">Exportar workspace</h3><p className="mt-1 text-[10px] text-muted">Plataformas, estratégias, planos, terminais e perfis de tela em JSON.</p></div></div><Button onClick={()=>void exportWorkspace()} className="mt-5 w-full bg-brand text-white"><Download size={14}/>Escolher local e exportar</Button></Card><Card className="p-5"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-lg bg-warning/10 text-warning"><ArchiveRestore size={19}/></div><div><h3 className="text-sm font-semibold">Importar e recuperar</h3><p className="mt-1 text-[10px] text-muted">Validação Zod e snapshot automático antes da mesclagem.</p></div></div><Button onClick={()=>void importWorkspace()} className="mt-5 w-full border-line bg-elevated text-ink"><Upload size={14}/>Selecionar arquivo JSON</Button></Card></div>
    <Card className="mt-3 p-5"><div className="flex items-center"><ShieldCheck size={18} className="mr-3 text-success"/><div><div className="text-sm font-semibold">Recuperação operacional</div><div className="mt-1 text-[10px] text-muted">WAL ativo • automação reinicia pausada • {diagnostics?.recoverySnapshots??0} snapshots de recuperação • {diagnostics?.screenProfiles??0} perfis de tela</div></div>{restartRequired&&<Button onClick={()=>void window.aviator.restartApp()} className="ml-auto bg-brand text-white"><RotateCw size={13}/>Reiniciar agora</Button>}{!restartRequired&&<CheckCircle2 size={18} className="ml-auto text-success"/>}</div></Card>
    <Card className="mt-3 overflow-hidden"><div className="border-b border-line p-4"><div className="text-sm font-semibold">Snapshots restauráveis</div><div className="mt-1 text-[10px] text-muted">Criados automaticamente antes de cada importação ou restauração.</div></div>{snapshots.map(snapshot=><div key={snapshot.id} className="flex items-center border-b border-line px-4 py-3 last:border-0"><ArchiveRestore size={15} className="mr-3 text-blue-300"/><div><div className="font-mono text-[10px]">{new Date(snapshot.createdAt).toLocaleString('pt-BR')}</div><div className="mt-1 text-[9px] text-muted">{snapshot.platforms} plataformas • {snapshot.terminals} Terminais</div></div><Button onClick={()=>void restore(snapshot.id)} className="ml-auto border-line bg-elevated text-ink">Restaurar</Button></div>)}{!snapshots.length&&<div className="p-5 text-center text-xs text-muted">Nenhum snapshot criado até agora.</div>}</Card>
    <Card className="mt-3 p-5"><div className="flex items-center"><div><div className="text-sm font-semibold">Benchmark de 10, 20, 50 e 100 Terminais</div><div className="mt-1 text-[10px] text-muted">Reprocessa até 500 rodadas com os mesmos motores, sem executar automação de tela.</div></div><Button onClick={()=>void runBenchmark()} disabled={benchmarking} className="ml-auto bg-brand text-white"><RefreshCw size={13} className={benchmarking?'animate-spin':''}/>{benchmarking?'Medindo...':'Executar benchmark'}</Button></div>{benchmark.length>0&&<div className="mt-4 grid grid-cols-4 gap-2">{benchmark.map(item=><div key={item.terminalCount} className="rounded-md border border-line bg-canvas p-3"><div className="label">{item.terminalCount} Terminais</div><div className="mt-2 font-mono text-sm font-bold">{item.durationMs.toFixed(1)} ms</div><div className="mt-1 font-mono text-[9px] text-muted">{item.evaluationsPerSecond.toLocaleString('pt-BR')} avaliações/s</div></div>)}</div>}</Card>
  </div>;
}
function Metric({label,value}:{label:string;value:number|undefined}){return <Card className="p-4"><div className="label">{label}</div><div className="mt-2 font-mono text-xl font-bold">{value??'...'}</div></Card>}
