import { useEffect, useState } from 'react';
import { ArchiveRestore, CheckCircle2, DatabaseBackup, Download, RefreshCw, RotateCw, ShieldCheck, Upload } from 'lucide-react';
import type { PerformanceBenchmarkResult, RecoverySnapshot, SystemDiagnostics } from '@aviator/shared';
import { Badge, Button, Card } from '@/components/ui';

export function SettingsPage() {
  const [diagnostics, setDiagnostics] = useState<SystemDiagnostics | null>(null);
  const [snapshots,setSnapshots]=useState<RecoverySnapshot[]>([]);
  const [benchmark,setBenchmark]=useState<PerformanceBenchmarkResult[]>([]);const[benchmarking,setBenchmarking]=useState(false);
  const [message, setMessage] = useState<string | null>(null);
  const [restartRequired, setRestartRequired] = useState(false);
  async function load() { const [result,recovery]=await Promise.all([window.aviator.getSystemDiagnostics(),window.aviator.listRecoverySnapshots()]); if(result.ok&&result.data)setDiagnostics(result.data);if(recovery.ok&&recovery.data)setSnapshots(recovery.data); }
  useEffect(()=>{void load()},[]);
  async function exportWorkspace(){const result=await window.aviator.exportWorkspace();if(result.ok&&result.data)setMessage(`Workspace exportado para ${result.data}`);}
  async function importWorkspace(){if(!window.confirm('A importação mesclará configurações com o workspace atual e criará um snapshot de recuperação. Continuar?'))return;const result=await window.aviator.importWorkspace();if(result.ok&&result.data){setMessage('Importação concluída. Reinicie para reconstruir todos os runtimes.');setRestartRequired(true);void load();}else if(!result.ok)setMessage(result.error??'Falha ao importar.');}
  async function restore(id:string){if(!window.confirm('Restaurar este snapshot? O estado atual também será preservado em um novo snapshot.'))return;const result=await window.aviator.restoreRecoverySnapshot(id);if(result.ok){setMessage('Snapshot restaurado. Reinicie para reconstruir os Terminais com segurança.');setRestartRequired(true);void load();}else setMessage(result.error??'Falha ao restaurar snapshot.');}
  async function runBenchmark(){setBenchmarking(true);const result=await window.aviator.runPerformanceBenchmark();setBenchmarking(false);if(result.ok&&result.data)setBenchmark(result.data);else setMessage(result.error??'Falha no benchmark.');}
  return <div className="p-5"><div className="mb-5 flex items-end justify-between"><div><h2 className="text-xl font-bold">Configurações e recuperação</h2><p className="mt-1 text-xs text-muted">Diagnóstico local, backup portátil e recuperação segura do workspace.</p></div><Button onClick={()=>void load()} className="border-line bg-panel text-muted"><RefreshCw size={13}/>Atualizar diagnóstico</Button></div>
    {message&&<div className="mb-3 rounded-md border border-brand/25 bg-brand/10 p-3 text-xs text-blue-100">{message}</div>}
    <div className="mb-3 grid grid-cols-3 gap-3"><Card className="p-4"><div className="flex items-center justify-between"><div><div className="label">Integridade SQLite</div><div className="mt-2 font-mono text-lg font-bold">{diagnostics?.databaseIntegrity??'...'}</div></div><Badge tone={diagnostics?.databaseIntegrity==='ok'?'success':'warning'}>{diagnostics?.databaseIntegrity==='ok'?'SAUDÁVEL':'VERIFICANDO'}</Badge></div></Card><Metric label="Rodadas persistidas" value={diagnostics?.rounds}/><Metric label="Eventos auditados" value={diagnostics?.eventLogs}/></div>
    <div className="grid gap-3 xl:grid-cols-2"><Card className="p-5"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-lg bg-brand/10 text-blue-300"><DatabaseBackup size={19}/></div><div><h3 className="text-sm font-semibold">Exportar workspace</h3><p className="mt-1 text-[10px] text-muted">Plataformas, estratégias, planos, terminais e perfis de tela em JSON.</p></div></div><Button onClick={()=>void exportWorkspace()} className="mt-5 w-full bg-brand text-white"><Download size={14}/>Escolher local e exportar</Button></Card><Card className="p-5"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-lg bg-warning/10 text-warning"><ArchiveRestore size={19}/></div><div><h3 className="text-sm font-semibold">Importar e recuperar</h3><p className="mt-1 text-[10px] text-muted">Validação Zod e snapshot automático antes da mesclagem.</p></div></div><Button onClick={()=>void importWorkspace()} className="mt-5 w-full border-line bg-elevated text-ink"><Upload size={14}/>Selecionar arquivo JSON</Button></Card></div>
    <Card className="mt-3 p-5"><div className="flex items-center"><ShieldCheck size={18} className="mr-3 text-success"/><div><div className="text-sm font-semibold">Recuperação operacional</div><div className="mt-1 text-[10px] text-muted">WAL ativo • automação reinicia pausada • {diagnostics?.recoverySnapshots??0} snapshots de recuperação • {diagnostics?.screenProfiles??0} perfis de tela</div></div>{restartRequired&&<Button onClick={()=>void window.aviator.restartApp()} className="ml-auto bg-brand text-white"><RotateCw size={13}/>Reiniciar agora</Button>}{!restartRequired&&<CheckCircle2 size={18} className="ml-auto text-success"/>}</div></Card>
    <Card className="mt-3 overflow-hidden"><div className="border-b border-line p-4"><div className="text-sm font-semibold">Snapshots restauráveis</div><div className="mt-1 text-[10px] text-muted">Criados automaticamente antes de cada importação ou restauração.</div></div>{snapshots.map(snapshot=><div key={snapshot.id} className="flex items-center border-b border-line px-4 py-3 last:border-0"><ArchiveRestore size={15} className="mr-3 text-blue-300"/><div><div className="font-mono text-[10px]">{new Date(snapshot.createdAt).toLocaleString('pt-BR')}</div><div className="mt-1 text-[9px] text-muted">{snapshot.platforms} plataformas • {snapshot.terminals} Terminais</div></div><Button onClick={()=>void restore(snapshot.id)} className="ml-auto border-line bg-elevated text-ink">Restaurar</Button></div>)}{!snapshots.length&&<div className="p-5 text-center text-xs text-muted">Nenhum snapshot criado até agora.</div>}</Card>
    <Card className="mt-3 p-5"><div className="flex items-center"><div><div className="text-sm font-semibold">Benchmark de 10, 20, 50 e 100 Terminais</div><div className="mt-1 text-[10px] text-muted">Reprocessa até 500 rodadas com os mesmos motores, sem executar automação de tela.</div></div><Button onClick={()=>void runBenchmark()} disabled={benchmarking} className="ml-auto bg-brand text-white"><RefreshCw size={13} className={benchmarking?'animate-spin':''}/>{benchmarking?'Medindo...':'Executar benchmark'}</Button></div>{benchmark.length>0&&<div className="mt-4 grid grid-cols-4 gap-2">{benchmark.map(item=><div key={item.terminalCount} className="rounded-md border border-line bg-canvas p-3"><div className="label">{item.terminalCount} Terminais</div><div className="mt-2 font-mono text-sm font-bold">{item.durationMs.toFixed(1)} ms</div><div className="mt-1 font-mono text-[9px] text-muted">{item.evaluationsPerSecond.toLocaleString('pt-BR')} avaliações/s</div></div>)}</div>}</Card>
  </div>;
}
function Metric({label,value}:{label:string;value:number|undefined}){return <Card className="p-4"><div className="label">{label}</div><div className="mt-2 font-mono text-xl font-bold">{value??'...'}</div></Card>}
