import { contextBridge, ipcRenderer } from 'electron';

contextBridge.exposeInMainWorld('aviator', {
  bootstrap: () => ipcRenderer.invoke('app:bootstrap'),
  login: (input: unknown) => ipcRenderer.invoke('auth:login', input),
  logout: () => ipcRenderer.invoke('auth:logout'),
  createTerminal: (input: unknown) => ipcRenderer.invoke('terminal:create', input),
  updateTerminal: (input: unknown) => ipcRenderer.invoke('terminal:update', input),
  duplicateTerminal: (id: string) => ipcRenderer.invoke('terminal:duplicate', id),
  deleteTerminal: (id: string) => ipcRenderer.invoke('terminal:delete', id),
  resetTerminal:(id:string,mode:'FINANCIAL'|'FULL')=>ipcRenderer.invoke('terminal:reset',{id,mode}),
  updateTerminalInitialBankroll:(id:string,initialBankrollCents:number)=>ipcRenderer.invoke('terminal:update-bankroll',{id,initialBankrollCents}),
  getTerminalHistory:(terminalId:string,limit=5000)=>ipcRenderer.invoke('terminal:history',{terminalId,limit}),
  setTerminalPaused: (id: string, paused: boolean) => ipcRenderer.invoke('terminal:set-paused', { id, paused }),
  setTerminalSchedulePlan: (terminalId:string,schedulePlanId:string|null)=>ipcRenderer.invoke('terminal:set-schedule-plan',{terminalId,schedulePlanId}),
  saveTerminalControlRule:(input:unknown)=>ipcRenderer.invoke('terminal-control-rule:save',input),
  deleteTerminalControlRule:(id:string)=>ipcRenderer.invoke('terminal-control-rule:delete',id),
  saveScreenProfile: (input: unknown) => ipcRenderer.invoke('screen-profile:save', input),
  captureScreenCoordinate: () => ipcRenderer.invoke('screen-profile:capture'),
  validateScreenProfile: (terminalId: string) => ipcRenderer.invoke('screen-profile:validate', { terminalId }),
  runScreenMock: (terminalId: string) => ipcRenderer.invoke('screen-profile:mock-run', { terminalId }),
  getScreenAutomationStatus: () => ipcRenderer.invoke('screen-automation:status'),
  setScreenAutomationPaused: (paused: boolean) => ipcRenderer.invoke('screen-automation:set-paused', { paused }),
  testScreenCoordinate: (terminalId: string, coordinateKey: string) => ipcRenderer.invoke('screen-automation:test-coordinate', { terminalId, coordinateKey }),
  testAssistedPreparation: (terminalId: string) => ipcRenderer.invoke('screen-automation:prepare-test', { terminalId }),
  createPlatform: (input: unknown) => ipcRenderer.invoke('platform:create', input),
  updatePlatform: (input: unknown) => ipcRenderer.invoke('platform:update', input),
  setPlatformEnabled: (id: string, enabled: boolean) => ipcRenderer.invoke('platform:set-enabled', { id, enabled }),
  testPlatform: (input: unknown) => ipcRenderer.invoke('platform:test', input),
  syncCollectorNow: (platformId: string) => ipcRenderer.invoke('collector:sync-now', platformId),
  getRecentRounds:(platformId:string|null,limit:50|100|250|500)=>ipcRenderer.invoke('rounds:recent',{platformId,limit}),
  getAiSettings:()=>ipcRenderer.invoke('ai:settings:get'),
  saveAiSettings:(input:unknown)=>ipcRenderer.invoke('ai:settings:save',input),
  testAiConnection:()=>ipcRenderer.invoke('ai:connection:test'),
  listAiModels:()=>ipcRenderer.invoke('ai:models:list'),
  sendAiChat:(input:unknown)=>ipcRenderer.invoke('ai:chat',input),
  runBacktest: (input: unknown) => ipcRenderer.invoke('backtest:run', input),
  listAudit: (input: unknown) => ipcRenderer.invoke('audit:list', input),
  getSystemDiagnostics: () => ipcRenderer.invoke('system:diagnostics'),
  getInterfaceScale: () => ipcRenderer.invoke('display:scale:get'),
  setInterfaceScale: (scale: number) => ipcRenderer.invoke('display:scale:set', scale),
  runPerformanceBenchmark:()=>ipcRenderer.invoke('system:benchmark'),
  listRecoverySnapshots:()=>ipcRenderer.invoke('recovery:list'),
  restoreRecoverySnapshot:(id:string)=>ipcRenderer.invoke('recovery:restore',id),
  exportWorkspace: () => ipcRenderer.invoke('workspace:export'),
  importWorkspace: () => ipcRenderer.invoke('workspace:import'),
  listConfigurations: (kind?: string) => ipcRenderer.invoke('configuration:list', { kind }),
  saveConfiguration: (input: unknown) => ipcRenderer.invoke('configuration:save', input),
  duplicateConfiguration: (id: string, kind: string) => ipcRenderer.invoke('configuration:duplicate', { id, kind }),
  deleteConfiguration: (id: string, kind: string) => ipcRenderer.invoke('configuration:delete', { id, kind }),
  restartApp: () => ipcRenderer.invoke('app:restart'),
  onDataChanged: (callback: () => void) => {
    const listener = () => callback();
    ipcRenderer.on('app:data-changed', listener);
    return () => ipcRenderer.removeListener('app:data-changed', listener);
  },
  windowMinimize: () => ipcRenderer.invoke('window:minimize'),
  windowMaximize: () => ipcRenderer.invoke('window:maximize'),
  windowClose: () => ipcRenderer.invoke('window:close')
});
